apiVersion: v1
kind: Pod
metadata:
 name: hello-world-app
 labels:
  name: hello-world-app
spec:
  containers:
  - name: localhost
    image: localhost:5000/hello-world-image
    ports:
    - containerPort: 3000
    volumeMounts:
    - name: mount-to-certs
      mountPath: /etc/ssl/app-test
    - name: mount-to-certs-private
      mountPath: /etc/ssl/app-test/private
  volumes:
  - name: mount-to-certs
    configMap:
      name: file12-config
  - name: mount-to-certs-private
    configMap:
      name: file3-config